### ISSUE TITLE
netDxf.Header.HeaderVariables.CustomNames()

### ISSUE THREAD

**Issue by johnau** [haplokuon/netDxf#112]
The method:
netDxf.Header.HeaderVariables.CustomNames()
returns a List<string> of variables.Keys, instead of customVariables.Keys

**Comment by haplokuon** [comment]
Fixed in netDxf 2.3.0

**Comment by johnau** [comment]
Thanks Daniel, nice work by the way :)
Are you considering moving to the System.Numerics Vector classes? I could
try to help :)

**Comment by haplokuon** [comment]
Please do not use an old issue to talk about a different topic, a lot less if it is about a bug that has been closed.

About your question, at the moment no, I have no plans to do it. As far as I know, Vector and Matrix classes were introduced in the net Framework 4.6 and I am using 4.5 for this library.
