### ISSUE TITLE
DimLinePosition retrun a wrong result

### ISSUE THREAD

**Issue by kchbpy** [haplokuon/netDxf#113]
When read the LinearDimension which is rotated in 90° or 270° will get a wrong result.
Here is a pic,the result is mirrored with real result.
![2019-06-27_105024](https://user-images.githubusercontent.com/26535277/60230715-74fb8580-98c9-11e9-8196-3ec8696bf0e8.jpg)

**Comment by kchbpy** [comment]
![2019-06-27_105024](https://user-images.githubusercontent.com/26535277/60230840-db80a380-98c9-11e9-9b9e-d7c6f5d5e457.jpg)

**Comment by haplokuon** [comment]
Where is the LinearDimension coming from? Are you using the latest netDxf release?

If it is coming from a DXF upload a sample file, I do not know which program are you using and I might not have it, I guess it is AutoCAD by the looks of the image.

If you are creating the LinearDimension programmatically post the code you are using to generate it.

For the time being, when your dimension line is parallel to the measured line, it is easier to use an AlignedDimension instead.

**Comment by kchbpy** [comment]
The LinerDimension is made by AutoCAD2016
In the pic below left:CMD right:AutoCAD2016
![wenti](https://user-images.githubusercontent.com/26535277/60313425-a475c500-9991-11e9-8bce-31456c22a6cc.jpg)
And here is the dxf file

[ddd.zip](https://github.com/haplokuon/netDxf/files/3337365/ddd.zip)

**Comment by haplokuon** [comment]
Ok, I uploaded a fix to the repository. It only affected Linear Dimensions loaded from a DXF and only under certain circumstances, it was related to the order of the reference points and the rotation. It should work know.

**Comment by kchbpy** [comment]
Thumbs up to you
