### ISSUE TITLE
tolerance value

### ISSUE THREAD

**Issue by Marcross91** [haplokuon/netDxf#118]
Goodmorning all,

i have some problem with getting tolerance value from a dimension.
I wrote this simple code in a button click with c#:

`openFileDialog1.ShowDialog();
            DxfDocument fileDXF = DxfDocument.Load(openFileDialog1.FileName);

            foreach (netDxf.Entities.Dimension quote in fileDXF.Dimensions) {

                listBox1.Items.Add(quote.DimensionType);
                listBox1.Items.Add(Math.Round(quote.Measurement, 2));
                listBox1.Items.Add(quote.Style.Tolerances.UpperLimit.ToString());
            }`

the listbox1 text is right for DimensionType and for Measurement but tolerance are ever equals to zero…

what am I doing wrong?

Thank you all

**Comment by haplokuon** [comment]
By default the dimension style tolerance upper and lower limit are zero. But if you have manually changed the dimension measurement tolerance values I will need to take a look at your DXF. Reading and writing those values works as expected.

**Comment by Marcross91** [comment]
Yes i manually changed the tolerance value.
This is the trial sample dxf file that i used for my little project with netDxf library.

[Trial.zip](https://github.com/haplokuon/netDxf/files/3473099/Trial.zip)

Thank you

**Comment by haplokuon** [comment]
You are trying to read the tolerance limit from the dimension style, but you have, actually, modified it individually. Therefore the information you seek is in the StyleOverrides list of the dimension.
```c#
double upperLimit = (double) dxfDocument.Dimensions.ElementAt(3).StyleOverrides[DimensionStyleOverrideType.TolerancesUpperLimit].Value;
```
In any case, I found a bug in how the tolerance display method of a dimension style override is saved to a file, I will fix that.

**Comment by Marcross91** [comment]
It works perfectly,

Thank you a lot
