### ISSUE TITLE
Move a EllipseArc will get wrong result

### ISSUE THREAD

**Issue by kchbpy** [haplokuon/netDxf#134]
### Here is the code:
```c#
Ellipse earc = new Ellipse(Vector2.Zero, 10, 5)     //pic1
            {
                StartAngle = 0,
                EndAngle = 180,
                Rotation = 180
            };

earc.TransformBy(Matrix4.Translation(5, 0, 0));      //pic2
```
### pic1
I draw a semi ellipse
![pic1](https://user-images.githubusercontent.com/26535277/66400942-f3150f80-ea14-11e9-84da-c7887b8ca0e2.jpg)
### pic2
After move the semi ellipse direction changed
![pic2](https://user-images.githubusercontent.com/26535277/66401063-1cce3680-ea15-11e9-9956-9dd662c526e6.jpg)

**Comment by haplokuon** [comment]
For the time being and before I upload a fix for it. You can, instead, create the ellipse arc from 180 to 0 with 0 rotation.
