### ISSUE TITLE
Feature request : Support for Rounded polygons

### ISSUE THREAD

**Issue by Sumeet2490** [haplokuon/netDxf#14]
One of the features I'm developing for my CAD generator needs to round the corners of a polygon.
Could you please suggest how can I do this?

Thanks!

**Comment by haplokuon** [comment]
You can easily build rounded polygons using the LwPolyline entity and the Bulge property of its vertices. First you will need to chamfer its corners and then set the bulge value accordingly for every other vertex.

The only entities you will find in the library are the ones present in the dxf database. This library does not pretend to solve geometric problems but to help reading and saving dxf files in a more meaningful way.

Daniel

**Comment by Sumeet2490** [comment]
Thanks for your response. Could you please give a code snippet? (like a rounded square with corner radius 1)

**Comment by haplokuon** [comment]
Please, try to work it out yourself first. Later, you can come back with your problems with something to show.

Daniel
