### ISSUE TITLE
Getting Text which lies inside bounding box

### ISSUE THREAD

**Issue by alison84r** [haplokuon/netDxf#149]
Hello,
I have a bounding box coordinates. Can I get all text inside the bounding box quickly by some method. 
Is there any direct method ?
Now I am checking each text lies inside the bounding box or not. Which is actually time consuming. 
Thanks in advance

**Comment by haplokuon** [comment]
No. The main problem here is to calculate the length of a text for TTF and SHX fonts, and also the height of the paragraphs for MText entities. Once this is known, the bounding box can be calculated, later find if it lies inside another is straightforward.

**Comment by alison84r** [comment]
Thanks
