### ISSUE TITLE
Quickly make dxf from autocad entities?

### ISSUE THREAD

**Issue by jmaeding** [haplokuon/netDxf#15]
At first I saw the front page example and thought, cool, just add acad entities to the dxf doc. Then I realized you add netdxf EntityObjects, not acad entities.
I then thought the clone method would make it easy but realized netdxf has nothing to do with reading dwg items. There are no autocad references, which is half the whole point of the library (you don't need acad to use it).
So now I do want to use it to convert a dwg to dxf. Do I have to make code to fill in netdxf entitiyobjects with acad entity info for each type? Surely someone has already done this at least for testing.
I don't see it though, must I write my own?
thanks

**Comment by sorifiend** [comment]
Personally I use the API for cloudconvert.com for dwg to dxf and the do all dxf manipulation with netDXF. 
If you want a good free library that does not rely on the web, then you will be hard pressed to find one, the best solution is simply to pay for one of the big ones.
