### ISSUE TITLE
Documentation regarding nuget?

### ISSUE THREAD

**Issue by ramubhai** [haplokuon/netDxf#162]
I was about to ask the official repository  when I found the closed issue https://github.com/haplokuon/netDxf/issues/156. 

It would be better if it is documented in README that only GITHUB is the official source. Even better if some guideline is there on how to use this library without nuget.

The one at https://www.nuget.org/packages/netDXF/ is from a 3rd party. If possible please publish an official Nuget.

**Comment by haplokuon** [comment]
If you have read that post you already know the answer. No, I have no plans of publishing anything at NuGet, if I change my mind I will make it public, this is all I have time for. And, no, I will not write in the Readme what this library is not or what does not do. Why don't you take over and maintain it? Contact the owner and keep it updated, if you are so interested on it.
