### ISSUE TITLE
Read / Write Layer States

### ISSUE THREAD

**Issue by jtoverka** [haplokuon/netDxf#206]
In netDxf.Tables.Linetype are two methods: load and save. These methods allow you to read/write Linetype data (.lin files). However, in netDxf.Tables.Layer such methods do not exist for Layer data (.las files). Can we add a feature to allow this? I inspected the layer state files that AutoCAD produces and it is just a small section that you would see from a dxf file.

**Comment by haplokuon** [comment]
I've taken a look at the layer states (.las files). That information is also stored inside the DXF as dictionaries and the .las file has a similar structure as the DXF. It should be feasible to implement them, but as a lot of stuff with the DXF the main problem is the lack of information about how exactly that information is stored.

**Comment by haplokuon** [comment]
Added in 2.4.1
