### ISSUE TITLE
Poyline "SmootType" or "Flags"

### ISSUE THREAD

**Issue by bayramakgul** [haplokuon/netDxf#212]
is there any way to get Poyline "SmootType" or "Flags"; because marked as private or internal.

**Comment by haplokuon** [comment]
That is not implemented, you can use the Spline entity for the same purpose.

**Comment by bayramakgul** [comment]
What should I do while reading an AcDb2dPolyline or AcDb3dPolyline object from an existing DXF file?

**Comment by haplokuon** [comment]
What you should do is come back here with less generic questions, be more specific. Read the DXF documentation and familiarize yourself with it, you can check the code of the library specially the method ReadPolyline of the DxfReader class to see how I am doing it.
