### ISSUE TITLE
LWPolyline.Reverse not working correct (bug)

### ISSUE THREAD

**Issue by spitfirekmt** [haplokuon/netDxf#216]
/// <summary>
        /// Switch the polyline direction.
        /// </summary>
        public void Reverse()
        {
            this.vertexes.Reverse();
        }

needs to be changed into something like:

LwPolyline _lwp = (DXFFile.LwPolylines[0]).Clone() as LwPolyline;
            lwp.Reverse();
            List<LwPolylineVertex> _oldvertexes = new List<LwPolylineVertex>(_lwp.Vertexes);

            _lwp.Vertexes.Clear();
            for (int i = 0; i < _oldvertexes.Count()-1; i++)
            {
                _lwp.Vertexes.Add(new LwPolylineVertex(_oldvertexes[i].Position, -_oldvertexes[i + 1].Bulge));
            }
            _lwp.Vertexes.Add(new LwPolylineVertex(_oldvertexes.Last().Position, -_oldvertexes[0].Bulge));

The reversed vertexes have to get the negative bulge of the next position. Atm the result has a high artistic value.

**Comment by haplokuon** [comment]
Yes, the bulge values need to be moved one place backwards after reversing the list of vertexes.

**Comment by haplokuon** [comment]
Resolved in 2.4.1
