### ISSUE TITLE
Hatch Edge fails on Arc?

### ISSUE THREAD

**Issue by deddolo** [haplokuon/netDxf#225]
I have a hatch composed of straight Lines and a portion of an open Arc.

When traversing the edges in the boundary path, they are all type line and the arc is ignored. Am I doing something wrong?
Funny enough, one edge has a random Z coordinate in it.

![image](https://user-images.githubusercontent.com/31637386/97121688-94d9ce00-16f6-11eb-96eb-f0513bc836b1.png)
![image](https://user-images.githubusercontent.com/31637386/97121714-bd61c800-16f6-11eb-83ad-5b92920d0251.png)

**Comment by haplokuon** [comment]
The edge HatchBoundaryPath.Polyline works like a LwPolyline, the Z value represent the bulge at that vertex. The arc edge you are looking for corresponds to that vertex with a non zero value for the Z coordinate.

**Comment by deddolo** [comment]
Okay. Thank you for the help. I ended up converting to LwPolyline and calling PolygonalVertex() to get a segmentation.
