### ISSUE TITLE
[Question] How can I read 'Line(s)' from a dxf file from a specific 'Layer'?

### ISSUE THREAD

**Issue by Sumeet2490** [haplokuon/netDxf#24]
I need to know the dimensions of all the Lines from a specific Layer(s).

Thanks for your time.

**Comment by sorifiend** [comment]
So, what have you tried so far?

It should be a simple matter of:
1) Loading the dxf file,
2) Getting all entities on that layer,
3) Then iterate through them and get the vector points for each line, and then do some quick math to get the dimensions you want.

**Comment by Sumeet2490** [comment]
Ah..Thanks! I was just not sure how to check the Layer (the 3rd point you mentioned)
