### ISSUE TITLE
Line types are read with an error

### ISSUE THREAD

**Issue by iborzenkov** [haplokuon/netDxf#250]
At class `Linetype` I see two methods for serializing the line type. 

I see an error when reading the value of `LinetypeSegmentRotationType.Absolute`
It is read using `"Q="` string  at `private static LinetypeSegment ReadLineTypeComplexSegment(string[] data, double length)` method:
```
else if (data[i].StartsWith("Q=", StringComparison.InvariantCultureIgnoreCase))
{
    rotationType = LinetypeSegmentRotationType.Absolute;
    rotation = ReadRotation(value);
}
```

It is written using another string `"A="` at `public void Save(string file)` method:
```
case LinetypeSegmentRotationType.Absolute:
    srt = "A=";
    break;
```

**Comment by haplokuon** [comment]
Yes, the Q is wrong it should be A for Absolute.
