### ISSUE TITLE
Filling of blocks

### ISSUE THREAD

**Issue by itcasth** [haplokuon/netDxf#251]
I parsed a DXF file, its block is filled with patterns, but I don't know how to solve it. It is a closed area composed of arc, curve and straight line. Tried a lot of methods, but the effect of filling is not ideal, I hope you can help me, had better have the relevant sample code, thanks!

**Comment by itcasth** [comment]
![image](https://user-images.githubusercontent.com/28160872/105284588-c0812d00-5bed-11eb-8997-9df6c599e277.png)

**Comment by haplokuon** [comment]
You will have to elaborate your question a lot more. Describe the problem and if you are working with an external DXF upload it, describe what you are doing, and post a sample code.
