### ISSUE TITLE
How to add arc through LwPolyline

### ISSUE THREAD

**Issue by itcasth** [haplokuon/netDxf#255]
Hello author, how to add arc through lwpolyline?

**Comment by itcasth** [comment]
I know that I can draw an arc through bulge, but I need to know the angle of the start point and the angle of the end point. How can I draw an arc through the coordinates of the start point, the coordinates of the end point and the center of the circle

**Comment by haplokuon** [comment]
Take a look at the method Explode of the LwPolyline it will show you how it is done, this method converts a lwpolyline into a set of lines an arcs. Also you can check the method PolygonalVertexes.

**Comment by itcasth** [comment]
Thank you very much！ I found that I can add arcs. Can I add multiple lines and arcs at the same time with one lwpolyline. Not through multiple lwpolylines

**Comment by itcasth** [comment]
Thanks! I've solved it
