### ISSUE TITLE
Error in UserText property

### ISSUE THREAD

**Issue by SpeedCAD** [haplokuon/netDxf#26]
Hi,

When I to suppress the text of a Dimension (one blank space) sends an error.

This code line sends an error:

`dim.UserText = " ";`

I had to correct it in the following way:

`List<string> texts = FormatDimensionText(measure, dim.DimensionType, dim.UserText, style, dim.Owner);`

`if (texts.Count == 0) texts.Add(dim.UserText);` **<- I added this line of code**

`MText mText = DimensionText(Vector2.Polar(midDim, style.TextOffset*style.DimScaleOverall, textRot + MathHelper.HalfPI), MTextAttachmentPoint.BottomCenter, textRot, texts[0], style);`

With this it works well, but, is there any other solution?

Regards

**Comment by haplokuon** [comment]
I uploaded a fix for this bug. Your modification will work fine, I just made a little change to the FormatDimensionText method to avoid adding the additional "if". Check the code if you are curious.

Daniel
