### ISSUE TITLE
How to get the attribute value of a block reference entity(Insert)?

### ISSUE THREAD

**Issue by 865390841** [haplokuon/netDxf#281]
Hello，This is a nice library to handle dxf file。
    And now i try to get the attribute value of a block reference entity that draw in AutoCAD 2016，but  got the empty string instead of the expected attribute value.
    Part of my code is as follows:
            var attributes = block.AttributeDefinitions;
            var attValues = attributes.Values;
            var lableStr = "UnInit";
            if (attValues.Count != 0)
            {
                lableStr = attValues.ElementAt(0).Value;
            }
    This is whether I use the right properties and classes，Thank you for your help。

**Comment by haplokuon** [comment]
Read [this](https://github.com/haplokuon/netDxf/issues/232) specially my last post.
