### ISSUE TITLE
Multiple Lines Attribute Definitions

### ISSUE THREAD

**Issue by tyrgin** [haplokuon/netDxf#30]
How can I set a "Multiple Lines" property of attribute to "Yes"?

**Comment by haplokuon** [comment]
You cannot, it is not implemented.

Daniel

**Comment by tyrgin** [comment]
Thank you for answer. 
Do you plan to do it?

**Comment by haplokuon** [comment]
Like with all feature request I will look it to it, but no promises.

Daniel

**Comment by tyrgin** [comment]
Sounds great, thank you!
