### ISSUE TITLE
Cannot load spline without control points

### ISSUE THREAD

**Issue by kryppel** [haplokuon/netDxf#302]
I have a file containing a spline with 3 fitpoints and no controlpoints. 

When trying to load the file i get an ArgumentException from the constructor in the Spline class. I tried to use the first and last fixpoint as controlpoints instead but when trying to create a PolyLine from that Spline I get an issue with missing Knots. 

Is there some kind of hack to generate the missing parts from the three known vertices?

**Comment by haplokuon** [comment]
I cannot reproduce your problem. Post the DXF giving you problems. An error, as you describe, should not be happening in the Spline constructor when loading a DXF file. If what you are trying to do is to build a Polyline from a Spline using the Polyline method, at the moment, you cannot do that if the Spline was created just from a set of fit points.
