### ISSUE TITLE
About comment in output file

### ISSUE THREAD

**Issue by is0263rf** [haplokuon/netDxf#305]
This library currently licensed under MIT license. But, default comment in output file says LGPL. Is there some kind of meaning to that?

https://github.com/haplokuon/netDxf/blob/e1b64e9f19f9e0fc7f72ed7b7b746f2682849561/netDxf/DxfDocument.cs#L164

**Comment by haplokuon** [comment]
I have changed the license a few months ago and I forgot to change that. Don't worry about it, you can easily edit, delete, and add your own comments.

**Comment by is0263rf** [comment]
Thank you. I sent pull request.

**Comment by haplokuon** [comment]
Thank you for your pull request, it won't be necessary, I already did the changes in my working copy. More programs should make use of the comments at least to identify its origin, even though they are not used in binary DXF files.

**Comment by is0263rf** [comment]
I see. My question was solved.
