### ISSUE TITLE
Support for complex linetypes

### ISSUE THREAD

**Issue by leowoods** [haplokuon/netDxf#31]
Hi,

Just a feature request to support complex line types, if it's possible.

In particular I use text in line types to represent contour lines in an export.  At the moment I've hacked something in, but it would be really useful for me if netDxf supported line types which contained text.

Thanks,

**Comment by haplokuon** [comment]
Like with all feature request I will look it to it, but no promises.

Daniel

**Comment by haplokuon** [comment]
Added in latest commit netDxf 2.1

Daniel
