### ISSUE TITLE
9 as a value of LUPrec

### ISSUE THREAD

**Issue by v-tsymbalistyi** [haplokuon/netDxf#313]
I have Autocad2000 dxf file which has 9 as a value of LUPrec header.
And based on [this](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a64.htm) 16-bit integer is a valid value. I know Autocad support 0-8 range (at least for 2022 version based on [this](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-5FFF39D6-EFC7-49F5-B56A-6023EB5C0DE7-htm.html?st=LUPrec)). But maybe it is possible to use the default value or round to accepted range instead of returning null as a result of DxfDocument.Load?

**Comment by haplokuon** [comment]
Yes, values that fall out side of the required range should reset to the default value. There are lots of similar cases like this.
