### ISSUE TITLE
Problem loading some dxf files 

### ISSUE THREAD

**Issue by pmorshed** [haplokuon/netDxf#319]
I have a dxf file that only contains one 3D FACE but I can not load it with: "_DxfDocument.Load(path)_"

Note-1: The problem is not 3D FACE. I deleted that (and purged the file) but the problem persisted.
Note-2: I changed the dxf file version but the problem persisted.
Note-3: This file was prepared by PDMS (a piping engineering software).

What is the problem? I have attached the file
[equip3.zip](https://github.com/haplokuon/netDxf/files/7215918/equip3.zip)
.

**Comment by haplokuon** [comment]
The DXF file you uploaded contains a multiline style with no name, that should never happen. I will add a workaround for that but, in any case, no program should allow to create nameless multiline styles like any other table object.
