### ISSUE TITLE
Any plans to port this to .net core?

### ISSUE THREAD

**Issue by donnyv** [haplokuon/netDxf#32]
.Net Core is starting to really heat up lately. Really was hoping to use this in a new project but its returning a null when trying to load a file. 

Curious if you have any plans to port it?

**Comment by haplokuon** [comment]
No, at the moment I have no plans about it.

If the Load method is returning null and your file is a valid dxf, you can use the Debug build if you want the library to throw any exception that might occur during the reading process. The thing is that, if the file is one of the compatible dxf versions, and the Load method still returns null there is nothing you can do. It might be a bad formatted file or a bug, in that case I will need to take a look at it to find a fix. But always check if the dxf is one of the supported versions, there are two methods in the class DxfDocument exactly for this purpose, called:

```c#
public static DxfVersion CheckDxfFileVersion(Stream stream, out bool isBinary)
```
or
```c#
public static DxfVersion CheckDxfFileVersion(string file, out bool isBinary)
```

Daniel

**Comment by donnyv** [comment]
The dxf file loaded fine using traditional .NET.

**Comment by donnyv** [comment]
So I gave it a try to port to .net core. Actually wasn't to hard. I had to add 2 dependencies though. Since .net core hasn't ported System.Drawing yet. I had to add SkiaSharp and LibTiff to support tiff files. Not too many changes. I'm not really sure how to commit this, so here is the entire project with the changes. Should work on linux and mac but haven't tested it. Works fine on Windows. 
http://gis.civilsolutions.biz/downloads/netDxf-master.NetCore.7z

**Comment by Becus25** [comment]
@haplokuon maybe you should adopt the changes from @donnyv .

**Comment by devel0** [comment]
Thanks to Microsoft.Windows.Compatibility nuget package you don't need to change any line of code apart to regenerate netdxf.csproj file by issueing `dotnet new classlib --name netDxf` in another folder and then move csproj over. Note that if you want to use netstandard 2 library directly from either net core and net framework the last one need to be at least 4.6.1. I wrote a [pull request](https://github.com/haplokuon/netDxf/pull/64) about and I noticed now there is another one for the same reason. More you can use visual studio code from any platform and work with dxf files.

**Comment by haplokuon** [comment]
Created a new branch with the project compatible with NET 5.0 the will eventually become the master.
