### ISSUE TITLE
The copyright comments in head of each file contains invalid characters

### ISSUE THREAD

**Issue by LeiYangGH** [haplokuon/netDxf#323]
This issue may be not so obvious, but it indeed annoying.
I'm using Chinese locale.
When opening the files, VS prompt error dialog about encoding
![error-dialog](https://user-images.githubusercontent.com/5386998/137243225-cfd96da9-718a-468e-8c7e-2b99e9fd4aca.JPG)
:

Then double click and see the **quotes** are incorrectly displayed:
![quotes](https://user-images.githubusercontent.com/5386998/137243280-1b788061-2551-40a7-a4e3-8cb8c311fc03.JPG)

**Comment by haplokuon** [comment]
I seems that when I pasted the copyright text the original place where I copied the text contained some weird characters, that appear invisible in my side, but strange characters show up when I change the encoding in the same places as you. Anyway, nothing serious, I will copy the text again.
