### ISSUE TITLE
conditional compilation #if !NET45 should be enhanced

### ISSUE THREAD

**Issue by LeiYangGH** [haplokuon/netDxf#329]
If install vs2019 on a new Win10, .net 4.5 won't be installed by default(and even cannot be installed). But .net 4.8 can be installed.

> netDxf\netDxf\IO\DxfReader.cs

```cshar
#if !NET45
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
#endif
```
The code won't compile if re-target the project to .net 4.5.2, 4.6.1, 4.8 etc.

**Comment by haplokuon** [comment]
If you need to target a different framework you will need to manually edit the "netdxf.csproj" file.

**Comment by LeiYangGH** [comment]
yes. but after editing it, the code won't compile. The best compability is you  just need change the csproj, without other code. This is just enhancement, though.

**Comment by haplokuon** [comment]
The only thing you need to do is to change the target framework for 4.5 'net45' for the framework  4.8 'net48' in both places of the netdxf.csproj. There is no need to rename the constant 'NET45', that is to handle the changes between the net framework 4 family and previous ones; and the net Standard, net Core, and net 5, and I guess later versions like net 6.

**Comment by LeiYangGH** [comment]
I have tried so i'm afraid not like that.
`Encoding.RegisterProvider` should be compiled under .net core, right?
In .net 4.8, for example, it cannot compile.

**Comment by LeiYangGH** [comment]
ok. i missed another NET45 in the csproj. So `NET45` here means 'non-standard', not the target framework itself, right? I think the problem is solved. Thanks!
