### ISSUE TITLE
Framework upgrade 4.8

### ISSUE THREAD

**Issue by JvzRdm** [haplokuon/netDxf#336]
I've recently upgraded to Visual Studio 2022, in this version the Framework 4.5 is no longer available.
Our application has been upgraded to the Framwork 4.8, right after the upgrade DXF could no longer be loaded because "DxfDocument.Load" always returns NULL.
With a local copy and upgrading the Framework to 4.8 "DxfDocument.Load" no longer returns NULL.

Will the project be available in the FrameWork 4.7 or 4.8?

**Comment by haplokuon** [comment]
Read [this](https://github.com/haplokuon/netDxf/issues/329).

**Comment by JvzRdm** [comment]
Thanks, was wondering if the project would get an update.
Ill manage a custom build
