### ISSUE TITLE
DXF-Write, DimensionStyleOverrides

### ISSUE THREAD

**Issue by hoellersbuero** [haplokuon/netDxf#343]
Hi,
When writing the DXF, those two DimensionStyleOverrideTypes are swapped.:
TolerancesLowerLimit with code 47 and TolerancesUpperLimit with code 48.
Should be 48 and 47 instead 47 and 48
(DxfWriter lines 3843 and 3847)

Regards,
Michael

**Comment by haplokuon** [comment]
This has already been fixed, read [this](https://github.com/haplokuon/netDxf/issues/312).
