### ISSUE TITLE
Cannot parse file - infinite loop

### ISSUE THREAD

**Issue by AsiaMartini** [haplokuon/netDxf#348]
I cannot parse this file.
Debugging the code, seems the procedure got stuck in an infinite loop, searching for a Polyface Mesh vertex (DxfReader.cs : 8483).

Can you please help me?
[file.zip](https://github.com/haplokuon/netDxf/files/7855722/file.zip)

**Comment by haplokuon** [comment]
Your file is broken beyond repair.
