### ISSUE TITLE
when to make new tag?

### ISSUE THREAD

**Issue by LeiYangGH** [haplokuon/netDxf#370]
Hi 

The latest tag release is about 1 year ago. and there are about 13 commits since then.
When do you consider a new tag? what criteria?

best regards,

**Comment by haplokuon** [comment]
No one knows. The latest code is always safe to use, it doesn't mean that it does not contain unexpected bugs.  I do not upload code that is a work in progress, that is why I upload few big commits.

**Comment by LeiYangGH** [comment]
thanks.
