### ISSUE TITLE
read large DXF file returns null

### ISSUE THREAD

**Issue by airsxue** [haplokuon/netDxf#381]
when I read below DXF files which includ about 1800+ entities, the netDXT always return null, coubld you please help with this? Thanks.
[Uploading 塑模加工图样例1800.ZIP…]()

**Comment by haplokuon** [comment]
The link does not point to your file.

**Comment by airsxue** [comment]
> The link does not point to your file.
That's OK, I guess it's the same reason with  #380, which didn't use the latest code.thanks a lot.
