### ISSUE TITLE
Block in block Error

### ISSUE THREAD

**Issue by sunrui19941128** [haplokuon/netDxf#411]
[ceshi4(1).zip](https://github.com/haplokuon/netDxf/files/9488663/ceshi4.1.zip)
Hello, I have a DXF file here. There is a polyline as a block and a circle as a block. These two blocks form a new block. After opening, the position is wrong, and the number of inserts printed out is only 1. The number of inserts seen in the DXF file is three

**Comment by haplokuon** [comment]
I do not see any problems. You have an Insert that references a block that contains two more inserts that references two other blocks. What you are building is a nested block a Parent-Childs tree structure. Only the parent (owner) Insert will appear at the document level, the other two belong to its parent (owner) and not to the document. You need to navigate through the tree structure to find them. Check the entities that belong to the block to go down the tree, and its owner to go up.

Why do you think that after opening the position is wrong? You might need to read #390.
