### ISSUE TITLE
Problem with AcDbPolyFaceMeshVertex

### ISSUE THREAD

**Issue by oak377** [haplokuon/netDxf#422]
Hello, 
I'm receiving a ArgumentOutOfRangeException: 'The polyface mesh faces list requires at least one face'
generated by the PolyfaceMesh constructor.
If I open the document with Autocad or other dwg/dxf CAD the file does not seem to contain any error so I'm wondering if it could be a condition not managed by the library.

The dxf file is the one attached 

[Prova_01.zip](https://github.com/haplokuon/netDxf/files/9888911/Prova_01.zip)

Thanks a lot!

**Comment by haplokuon** [comment]
As the error suggested your file contains several Polyface meshes with unexpected bad geometry, next time they will be automatically removed. Soon I will upload an update.
