### ISSUE TITLE
Page setup data not preserved (PLOTSETTINGS?)

### ISSUE THREAD

**Issue by waryhermit** [haplokuon/netDxf#43]
Page setup of template file before saving with netDXF:

![image](https://user-images.githubusercontent.com/5189447/41122131-90d53ac0-6a68-11e8-9304-49685b17fac0.png)

Page setup after saving with .netDxf:
![image](https://user-images.githubusercontent.com/5189447/41122161-aa14064c-6a68-11e8-8c2d-656215dc0c91.png)

In the zip file there are two files:

- test.dxf - This is the template file after my program has used .netDxf to generate the model. The plotting information seems gone.
- testWithPageSetup.dxf - This is the file after I have gone back and added the page setup again (Plot extents, fit to page.)

[Output Drawings.zip](https://github.com/haplokuon/netDxf/files/2081869/Output.Drawings.zip)

**Comment by haplokuon** [comment]
There are some properties missing in the PlotSettings class, nothing serious, pretty straightforward. I will add them in next update.

Daniel

**Comment by waryhermit** [comment]
Excellent, thank you.

**Comment by haplokuon** [comment]
All PlotSettings parameters should be now available.

Daniel
