### ISSUE TITLE
Hidden layer identifying... I had read DXF document there is mentioned where colour code value is negative number to identify hidden layer 

### ISSUE THREAD

**Issue by Dharmesh1979** [haplokuon/netDxf#430]
Hi,
Another query is it true which I got ref. in DXF document for hidden layer state to identify where colour code value is negative number?

How to achieve this using this library?

**Comment by haplokuon** [comment]
Just check the IsVisible property of the Layer.

**Comment by Dharmesh1979** [comment]
Ok Thank you.
