### ISSUE TITLE
Hi,how to read the insert's clip boundary?

### ISSUE THREAD

**Issue by wolfsky7** [haplokuon/netDxf#433]
![image](https://user-images.githubusercontent.com/1808416/218043577-489100bb-89c2-417b-96a8-13903122fcf5.png)
[clip2.zip](https://github.com/haplokuon/netDxf/files/10705419/clip2.zip)

**Comment by DavidWishengrad** [comment]
Hi,
Have you done a search in the TestDxfDocument for boundary? There are several examples of creating hatch boundaries. Maybe the block does not have one assigned? Creating a clip and adding one to a block can be combined, but are separate.

You can always fall back on exploding the block (insert) and parsing the entities it contains and read the data that way.

Your dxf does not open for me: Unknown value "AC1032" encountered in drawing version.
Invalid or incomplete DXF input -- drawing discarded.

**Comment by wolfsky7** [comment]
Thank you for your reply.
I readed the examples,but It's not hatch boundaries.Can't find the clip data  when i explode the insert.
it is created by these steps:
1.Input the Command "Clip" in the cmmand line
2.choose the insert;
3.draw a path。

In Dwg Format can read it by the [link](https://help.autodesk.com/view/OARX/2021/ENU/?guid=GUID-72029044-0840-4187-9A58-F2A4518E3A23)

**Comment by DavidWishengrad** [comment]
Perhaps NetDXF does not support that?

**Comment by haplokuon** [comment]
You cannot, not implemented. The data generated by the AutoCad's CLIP command is stored as a SPATIAL_FILTER deep inside the poorly documented OBJECTS section, just like a plethora of other features.

**Comment by wolfsky7** [comment]
> plethora

Thanks for your reply.
