### ISSUE TITLE
Does netDxf process region?

### ISSUE THREAD

**Issue by my88480** [haplokuon/netDxf#446]

**Comment by haplokuon** [comment]
@DavidWishengrad

Perhaps BricsCAD uses the Autodesk RealDWG SDK. It is a library to read and write DXF and DWG files published by Autodesk but it is behind an outrageous pay wall, something that all companies should release for free. My main issue is that the sole owner of the file generated by a program holding your data its you, and companies must provide a way to be able to read your data without the use of their software. Ideally it will and SDK freely available, but at least . It is not like nobody does it Autodesk should learn from what Adobe has done with the PSD and PDF format or Microsoft with the DOC and DOCX; and it is not like it has hindered their business.

No, I do not know Mick Dupree and I agree. Abusive copyrights, patents, research papers behind hefty pay walls (knock knock Elsevier) this is what hinders innovation. That is why AutoCAD is no more than a glorified 2D drawing program.

And this is getting out of topic.
