### ISSUE TITLE
dxf load is empty

### ISSUE THREAD

**Issue by cooalzjc** [haplokuon/netDxf#460]
DxfDocument dxf = DxfDocument.Load(url);
dxf = null

But with CAD it can be opened。
![image](https://github.com/haplokuon/netDxf/assets/62917805/7ad3ceb4-dea9-4864-8dd5-492aefbe00a3)
[Drawing1(1)(1).zip](https://github.com/haplokuon/netDxf/files/11752512/Drawing1.1.1.zip)
Does anyone know why

**Comment by haplokuon** [comment]
You have uploaded a DWG not a DXF.

**Comment by DavidWishengrad** [comment]
It even says dwg 2x in the picture too.
