### ISSUE TITLE
Finding the Center of a Circle

### ISSUE THREAD

**Issue by Kimjs007** [haplokuon/netDxf#461]
![111](https://github.com/haplokuon/netDxf/assets/137267983/2d85d08b-31a3-46b0-8ca7-0bb8724f9bbc)
![22222](https://github.com/haplokuon/netDxf/assets/137267983/2f34cbb5-77b6-4eca-af77-2859f7149031)
![33333](https://github.com/haplokuon/netDxf/assets/137267983/b6e5c9d8-0638-47f5-a1ff-f31ba2635725)
![4444](https://github.com/haplokuon/netDxf/assets/137267983/d7c0e7bc-a0fc-429a-8a02-5041a93dc73d)

How can I access it from code in C#?

I want to put the X,Y center coordinates in the declared variable

**Comment by DavidWishengrad** [comment]
The easiest one is take the time to review the netDXF project. In it you will find many samples of accessing to properties of objects with different methods. Whichever one a person uses depends on them. You are sitting on a treasure trove of information and examples.

**Comment by Kimjs007** [comment]
I've been looking for examples, but I can't find any part of the C# code that accesses an entity and stores the circle's center point in a local variable.

Help me

**Comment by DavidWishengrad** [comment]
You will need to extract what you need from this.
Please note that the only reason I was able to do this is because accessing the entity collection like this is in the samples.

You really should read the entire source code and the samples in it, end to end, and every single report here.

This is from some source I have...

                 string layername = "";
                int roundamount = 16;
                int defaultroundamount = 16;
                int roundamounttouse = 16;

                double circlecenterx;
                double circlecentery;
                double circlecenterz;
                double circlerad;


DxfDocument loaded = DxfDocument.Load("C:\\Log\\fix.dxf");
loaded.Entities.ActiveLayout = netDxf.Objects.Layout.ModelSpaceName;
EntityCollection entitiesBlocks = loaded.Blocks[Block.DefaultModelSpaceName].Entities;







             foreach (Circle mycircle in entitiesBlocks.OfType<Circle>())
                {
                    layername = mycircle.Layer.Name;
                    string layernameupper = layername.ToUpper();
                    Layer layercheck = new Layer(layername);
                    layercheck.IsLocked = false;
                    layercheck.IsFrozen = false;

                    //go through ini and look for default round amount and set it
                    for (int i = 0; i < readinilinescleaned.Count; i++)
                    {
                        if (readinilinescleaned[i] == "DEFAULT")
                        {
                            //this only sets the round value for anthing else not on a layer in the ini
                            //convert string to double  
                            defaultroundamount = Convert.ToInt16(readinilinescleaned[i + 1]);
                            roundamounttouse = defaultroundamount;
                            break; //got it so leave
                        }
                    }

                    //compare layer names in the readinilinescleaned from the ini to the current object
                    //and set its round amount or skip it over if not listed and used the default already set (it resets ever object
                    for (int j = 0; j < readinilinescleaned.Count; j++)
                    {
                        string layerread = readinilinescleaned[j];
                        if (layernameupper == layerread)
                        {
                            if (readinilinescleaned[j + 2] == "1")
                            {
                                //skip this object on this layer and go to next object
                                goto nextcircle;
                            }
                            else
                            {
                                //get round amount and use it for this object
                                roundamounttouse = Convert.ToInt16(readinilinescleaned[j + 1]);
                                goto processcircle;
                            }
                        }
                        j = j + 2;
                    }

                processcircle:;

                    double verXonfirstpass;
                    double verYonfirstpass;
                    double verXdifference;
                    double verYdifference;
                    Vector3 center = new Vector3(1, 2, 0);
                    // double radius = 2.42548;


                    circlerad = mycircle.Radius;
                    circlerad = Math.Round(circlerad * roundamounttouse, 0) / roundamounttouse;

                    if (verXdifferenceX == 0)
                    {
                        circlecenterx = mycircle.Center.X; 
                        verXonfirstpass = circlecenterx; //store it for later
                        circlecenterx = Math.Round(circlecenterx * roundamounttouse, 0) / roundamounttouse;
                        verXdifferenceX = circlecenterx - verXonfirstpass; //get x difference between where it is and where it will be    
                    }
                    else
                    {
                        circlecenterx = mycircle.Center.X + verXdifferenceX;
                        circlecenterx = Math.Round(circlecenterx * roundamounttouse, 0) / roundamounttouse;
                    }

                    if (verYdifferenceY == 0)
                    {
                        circlecentery = mycircle.Center.Y;
                        verYonfirstpass = circlecentery; //store it for later
                        circlecentery = Math.Round(circlecentery * roundamounttouse, 0) / roundamounttouse;
                        verYdifferenceY = circlecentery - verYonfirstpass; //get y difference between where it is and where it will be    
                    }
                    else
                    {
                        circlecentery = mycircle.Center.Y + verYdifferenceY;
                        circlecentery = Math.Round(circlecentery * roundamounttouse, 0) / roundamounttouse;
                    }

                    circlecenterz = mycircle.Center.Z;
                    circlecenterz = 0; //flatten

                    center.X = circlecenterx;
                    center.Y = circlecentery;
                    center.Z = circlecenterz;

                    if (circlerad < .03125)
                        circlerad = .0625;

                    //Circle circle = new Circle(center, radius);
                    mycircle.Center = center;
                    mycircle.Radius = circlerad;
                nextcircle:;
                }

Now... here is openai...

Public Class DXFParser
    Public Shared Sub ParseCircles(filePath As String)
        Dim dxfDocument As DxfDocument = DxfDocument.Load(filePath)

        Dim circlePropertiesList As New List(Of CircleProperties)()

        For Each entity As netDxf.Entities.Entity In dxfDocument.Blocks.Item("*Model_Space")
            If TypeOf entity Is netDxf.Entities.Circle Then
                Dim circle As netDxf.Entities.Circle = DirectCast(entity, netDxf.Entities.Circle)

                Dim circleProperties As New CircleProperties()
                circleProperties.Layer = circle.Layer
                circleProperties.CenterX = circle.Center.X
                circleProperties.CenterY = circle.Center.Y
                circleProperties.CenterZ = circle.Center.Z
                circleProperties.Radius = circle.Radius
                circleProperties.Color = circle.Color.Index
                circleProperties.HandleId = circle.Handle.ToString()
                circleProperties.ObjectId = circle.Id.ToString()
                circleProperties.LineWeight = circle.LineWeight
                circleProperties.Linetype = circle.Linetype.Name

                circlePropertiesList.Add(circleProperties)
            End If
        Next

        ' Do something with the circlePropertiesList here
        ' For example, print the properties to the console
        For Each circleProperties As CircleProperties In circlePropertiesList
            Console.WriteLine("Layer: " & circleProperties.Layer)
            Console.WriteLine("Center X: " & circleProperties.CenterX)
            Console.WriteLine("Center Y: " & circleProperties.CenterY)
            Console.WriteLine("Center Z: " & circleProperties.CenterZ)
            Console.WriteLine("Radius: " & circleProperties.Radius)
            Console.WriteLine("Color: " & circleProperties.Color)
            Console.WriteLine("Handle ID: " & circleProperties.HandleId)
            Console.WriteLine("Object ID: " & circleProperties.ObjectId)
            Console.WriteLine("Line Weight: " & circleProperties.LineWeight)
            Console.WriteLine("Linetype: " & circleProperties.Linetype)
            Console.WriteLine()
        Next
    End Sub
End Class
