### ISSUE TITLE
Getting lines vertices

### ISSUE THREAD

**Issue by ghost** [haplokuon/netDxf#474]
Is there a discord or a clean documentation ?
I know how to get lines and segments, but it doesn't give you any vertices, so it's pretty meaningless for redrawing it in unity

**Comment by Kanhoto** [comment]
Forget that I found what I was doing wrong

I was using doc.entities.all instead of their sub type like doc.entities.lines, doc.entities.circles, etc...

**Comment by haplokuon** [comment]
There is nothing wrong calling All, it returns the full list of entities in the drawing in the order that they appear in the DXF, but you will have to cast the base EntityObject to its specific class. If you need to operate with multiple entity types it is the recommend way. The subtype properties returns a list of the specified entity using Linq from the same list as All. You will have to test which way is faster for you.

**Comment by Kanhoto** [comment]
I want to redraw so I may need to use all, since I don't want something that is supposed to overlap things to be overlapped instead because I'm drawing them in another order
