### ISSUE TITLE
Error when loading a file created with netDxf

### ISSUE THREAD

**Issue by xaotix** [haplokuon/netDxf#479]
When I try to load this file who was created with netDxf, returns an error.
[BG_NORMAL_R02.MDJ5.M03.zip](https://github.com/haplokuon/netDxf/files/12478248/BG_NORMAL_R02.MDJ5.M03.zip)

Line 10764 from DxfReader.cs
=> this.doc.Blocks.GetReferences(ownerRecord.Name)

ownerRecord.Name is "*PAPER_SPACE"

"The given key was not present in the dictionary. "

`   
   em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   em netDxf.Collections.TableObjects`1.GetReferences(String name)
   em netDxf.IO.DxfReader.ReadLayout()
   em netDxf.IO.DxfReader.ReadObjects()
   em netDxf.IO.DxfReader.Read(Stream stream, SupportFolders supportFolders)
   em netDxf.DxfDocument.Load(String file, IEnumerable`1 supportFolders)
   em netDxf.DxfDocument.Load(String file)
`

**Comment by haplokuon** [comment]
I forgot to make the key of the references dictionary in the TableObjects class case independent. This is a bad bug that can potentially affect a lot of people, I have uploaded a fix for this.

Your DXF file was not created by this library, unless another file was loaded and saved again with an older version. I do not use all caps for the "*PAPER_SPACE" name, and that is why loading your file fails. TableObject names are case independent.

**Comment by xaotix** [comment]
Sorry for my bad explanation.
The file was edited and saved with netDxf.

**Comment by haplokuon** [comment]
Don't worry, it was a nasty bug nonetheless.
