### ISSUE TITLE
How do I iterate over all entities in a parsed DXF file?

### ISSUE THREAD

**Issue by kub1x** [haplokuon/netDxf#48]
I've looked through the code but struggle to figure out, how to iterate over all entities in a parsed DXF file. 

Is there some single collection containing all the DxfSomething objects? I'd expect something like `dxfDocument.Entities` which would be similar to https://github.com/IxMilia/Dxf .

**Comment by haplokuon** [comment]
Yes, you can, they are organized by Layouts, netDxf supports not only the Model view but also the multiple Paper views that may exist. A DXF is made of multiple layouts, one ModelSpace layout called "Model" and multiple PaperSpace layouts. 

So to access the list of entities ordered as they appear in the DXF, you need to access the layout list, as follows:
```c#
DxfDocument doc = DxfDocument.Load("sample.dxf");
foreach (Layout layout in doc.Layouts)
{
    List<DxfObject> entities = doc.Layouts.GetReferences(layout);
    foreach (DxfObject o in entities)
    {
        EntityObject entity = o as EntityObject;
    }
}
```
If you only need the entities in the ModelSpace, you can access them directly with:
```c#
List<DxfObject> entities = doc.Layouts.GetReferences(Layout.ModelSpaceName);
```

Daniel
