### ISSUE TITLE
is possible working this library with IronPython?

### ISSUE THREAD

**Issue by xyont** [haplokuon/netDxf#481]
hi,

is possible to call and loading the library from IronPython? i give a try but thrown some error messages.

regards,

![2023-10-10 03_48_17-test16 py - SciTE](https://github.com/haplokuon/netDxf/assets/72367311/5f29f17b-4ff2-4c04-b648-313bd73b2e58)

**Comment by haplokuon** [comment]
I cannot think of a reason why it should not work, this is a pretty standard net library after all; but I have no experience with IronPython. Try to explicitly import the netDxf.Entities namespace where the circle class resides or use the full namespace netDxf.Entities.Circle to instantiate a Circle object. Same thing applies to similar cases.

You are also using an old version of this library, update it just in case.

**Comment by xyont** [comment]
thank you for the hints and giving such as guidance, it seems almost work except in `DxfDocument `to add entity.

![2023-10-10 14_53_03-test16 py - SciTE](https://github.com/haplokuon/netDxf/assets/72367311/14ce8514-9049-47a2-b63e-7184f23d4f20)

**Comment by haplokuon** [comment]
The AddEntity method does not exist anymore, I changed that long time ago. This is how I knew that you were using an old version of the library, now you can find it in dxf.Entities.Add.

Check the samples, check the documentation, and pay attention to the error IronPython is returning.

**Comment by xyont** [comment]
i downloaded from NuGet [here](https://www.nuget.org/packages/netDxf), there's only one matched. 

![2023-10-11 02_44_58-netDxf dll Properties](https://github.com/haplokuon/netDxf/assets/72367311/326bd3f9-a1de-4bb4-a6dc-8628fa6eb39f)

where's the latest DLL versions link to download?

**Comment by haplokuon** [comment]
Download the latest source code and build the library yourself. I am not related in any way, shape, or form with the nuget releases.

**Comment by xyont** [comment]
hi,

it seems the problem solved., thanks again for latest hint about `dxf.Entities.Add` now is working, so many thanks for all.

![2023-10-11 02_56_43-nanoCAD 5](https://github.com/haplokuon/netDxf/assets/72367311/0626db44-8607-400e-8bd7-f64114b926ce)

sorry for confusing of my mixed example from previous versions of the libraries.

regards,
