### ISSUE TITLE
Support for Header Variables $UCSXDIR and $UCSYDIR

### ISSUE THREAD

**Issue by Troubadix75** [haplokuon/netDxf#5]
Hello,

please add support for the Header Variables $UCSXDIR and $UCSYDIR
They are documented here: [http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A](http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A)

It would be really great if all coordinates could already respect these Variables. Thus no transformation has to be done by the user of the library.

**Comment by haplokuon** [comment]
I will take a look at it.

Daniel

**Comment by haplokuon** [comment]
Added in [2017/11/28]

**Comment by Troubadix75** [comment]
Hello Daniel,

Thank you for the quick implementation.

Thomas
