### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mizuno-gsinet** [haplokuon/netDxf#53]
Do you mind if you release netDxf under a license such as [MPL-2.0](https://opensource.org/licenses/MPL-2.0) rather than LGPL-2.1, so that it will be easier to use?

**Comment by haplokuon** [comment]
As long as I am maintaining and updating the netDxf library I will keep the LGPL license, if in the future I end up supporting it I will change it to something like MIT or alike.

Daniel

**Comment by mizuno-gsinet** [comment]
OK, thank you for expressing your thoughts. I hope you will keep on updating this awesome library!
