### ISSUE TITLE
Operating on the IsFrozen Property of layers in Viewport

### ISSUE THREAD

**Issue by txytju** [haplokuon/netDxf#6]
I have created a viewport in a layout and use it to see the objects from the model-space. But I didn't find a way to get the layers of the viewport, and because of this I can't control the IsFrozen property of the layers. So is there a way to freeze a layer in the viewport? Thank you!

**Comment by haplokuon** [comment]
The layer list is global and shared among all viewports. So, the value of the IsFrozen property of a layer will affect all viewports. If what you need is to freeze a layer in a specific viewport you need to add it to the viewport's FrozenLayers list.

Daniel
