### ISSUE TITLE
MText parsing issue

### ISSUE THREAD

**Issue by PetrMahdalicek** [haplokuon/netDxf#65]
Hello,
I found a dxf file with mtext, that is not parsed the right way.
I found this code in DxfReader.cs at line 8066:

`// text dxf files stores the tabs as ^I in the MText texts, they will be replaced by the standard tab character
            if (!this.isBinary)
            {
                textString = textString.Replace("^I", "\t");             
            }`
changing that to:
`if (!this.isBinary)
            {
                textString = textString.Replace("^I", "\t");
                textString = textString.Replace("^J", "\r\n");
            }`
will fix the parsing for me, but that is just a guess. I could not find any information about ^I and ^J symbols in mtext. 

Can you please have a look at it. 

Thank you
Petr

[test.zip](https://github.com/haplokuon/netDxf/files/2471705/test.zip)

**Comment by haplokuon** [comment]
The MText reader is fine. The text of a MText entity might contain lots of different kinds of codes that describe things like the text color, style, paragraph alignment, etc... In your case appears an undocumented code, at least I have not seen it before, that represents an end paragraph code. The MText uses @"\P" to describe the end paragraph, and I will substitute, from now on, the "^J" by @"\P".

I am not surprised that you have not find any information about those symbols, me neither, there is a lot of information about the DXF that is completely undocumented, and I end up implementing it by pure trial and error.

Daniel
