### ISSUE TITLE
Project is currently not Strongly-Named

### ISSUE THREAD

**Issue by peSHIr** [haplokuon/netDxf#84]
I started out using the netDXF NuGet package, but as all our own assemblies are strongly named, our code would not compile as the NuGet package is not strongly named. Checking the sources on here on github, I find that the original project is not strongly named either. Could you please make the project strongly named, so as not to exclude projects that are strongly named from easily re-using this code without having to be forced to do own compilation and update/version managing in the future?

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

**Comment by haplokuon** [comment]
I never cared to much about it, and nobody asked about it before. I will look it to it. Nevertheless the source code will always be available in case of special needs.

**Comment by peSHIr** [comment]
Yes, you're right. Was able to use the source code, in a namepace of my own
with a strong name of my own. Still, being about to reuse the proper
downloadable assembly with the "official" namespace would be preferable. If
you ever get round to it.

Op di 26 feb. 2019 16:10 schreef Daniel Carvajal <notifications@github.com>:

**Comment by haplokuon** [comment]
The new binaries in the netDxf 2.3.0 release are now strongly named, hope this is what you need.

**Comment by peSHIr** [comment]
Will have a look on Monday. If this indeed enables me to simply use a NuGet
assembly reference instead of including the source code in an assembly of
my own I will switch in a heartbeat. Thanks in advance!

Op zo 23 jun. 2019 10:42 schreef Daniel Carvajal <notifications@github.com>:

**Comment by haplokuon** [comment]
Keep in mind that I do not publish the library through NuGet, all I do is here at Github. It is another user who maintains the NuGet package.
