### ISSUE TITLE
 DxfDocument.CheckDxfFileVersion crash

### ISSUE THREAD

**Issue by seatrix** [haplokuon/netDxf#86]
CheckDxfFileVersion will return null when open these two files .
[crash.zip](https://github.com/haplokuon/netDxf/files/2887999/crash.zip)

**Comment by haplokuon** [comment]
Sometimes I am amazed of where do you get those files. After digging a little outside the official DXF documentation, I found a more complete list of the DXF drawing database codes back to version 1.0.

One of your files has the code "AC2.10" that version is from the ancient AutoCad 2.1, and it must be from the end of the 80s or the beginning of the 90s. The second file has the code AC1008 haven't found anything about that code, perhaps is it a beta or an internal version? I don't know. In any case both files has the structure of the files prior to AutoCad2000 and netDxf will not read them.

Having said that the CheckDxfFileVersion should at least return Unknown, I'll fix that.

**Comment by haplokuon** [comment]
Fixed in netDxf 2.3.0
