### ISSUE TITLE
Mirrored shapes are broken

### ISSUE THREAD

**Issue by SamuelLordBlack** [haplokuon/netDxf#95]
You force widthFactor to be positive, but this is wrong. A negative widthFactor indicates the object was mirrored, and that information must not be discarded. Both the parser (in ReadShape()) and the Shape entity should be fixed.

**Comment by haplokuon** [comment]
I am still working in allowing negative scaling.

**Comment by haplokuon** [comment]
Fixed in netDxf 2.3.0
