### ISSUE TITLE
Radial/Diametric dimension prefix isn't displayed in AutoCAD

### ISSUE THREAD

**Issue by Ars3i** [haplokuon/netDxf#97]
Radial and Diametric dimensions don't display the "R" or "Ø" prefix. Tested in AutoCAD 2012 and 2016. 
It's probably caused by this sequence in AcDbDimStyleTableRecord:

**3
<>**

If I manually delete these two lines from a dxf file. The problem is gone.

Original:
![original](https://user-images.githubusercontent.com/48828450/54823669-d39cdc00-4ca8-11e9-9b29-e25c9b52cf73.png)

Modified:
![modified](https://user-images.githubusercontent.com/48828450/54823678-db5c8080-4ca8-11e9-93f4-eec394c325b6.png)

[dimension drawing.zip](https://github.com/haplokuon/netDxf/files/2996478/dimension.drawing.zip)

**Comment by haplokuon** [comment]
Correct, no need to delete both lines just the <>. The DXF code 3 for the dimension style represents the combination of the prefix and suffix strings defined in the style. The characters <> are substituted by the actual dimension measurement but it is only required if the a prefix is present. I will fix it.

**Comment by haplokuon** [comment]
Fixed in netDxf 2.3.0
